import html
import re

import uuid
import streamlit as st
import streamlit_mermaid as stmd
from langchain.callbacks.base import BaseCallbackHandler


def append_message(content, role="assistant"):
    """Appends a message to the session state messages."""
    #if content.strip():
    print(content)
    st.session_state.messages.append({"role": role, "content": content})

def format_message(text):
    """
    This function is used to format the messages in the chatbot UI.

    Parameters:
    text (str): The text to be formatted.
    """
    text_blocks = re.split(r"```[\s\S]*?```", text)
    code_blocks = re.findall(r"```([\s\S]*?)```", text)

    text_blocks = [html.escape(block) for block in text_blocks]

    formatted_text = ""
    for i in range(len(text_blocks)):
        formatted_text += text_blocks[i].replace("\n", "<br>")
        if i < len(code_blocks):
            formatted_text += f'<pre style="white-space: pre-wrap; word-wrap: break-word;"><code>{html.escape(code_blocks[i])}</code></pre>'

    return formatted_text


def message_func(text,role): #is_user=False, is_df=False
    """
    This function is used to display the messages in the chatbot UI.

    Parameters:
    text (str): The text to be displayed.
    is_user (bool): Whether the message is from the user or not.
    is_df (bool): Whether the message is a dataframe or not.
    """
    is_user = False
    is_df = False
    is_image = False
    is_lineage = False

    if role == "user":
        is_user = True
    elif role == "data":
        is_df = True
    elif role == "image":
        is_image = True
    elif role == "lineage":
        is_lineage = True


    if is_user:
        avatar_url = "https://avataaars.io/?avatarStyle=Transparent&topType=Hat&accessoriesType=Blank&facialHairType=BeardLight&facialHairColor=Black&clotheType=BlazerSweater&eyeType=Default&eyebrowType=DefaultNatural&mouthType=Smile&skinColor=Light"
        message_alignment = "flex-end"
        message_bg_color = "linear-gradient(90deg, hsla(350, 73%, 44%, 1) 0%, hsla(274, 65%, 12%, 1) 100%);"

        avatar_class = "user-avatar"
        st.write(
            f"""
                <div style="display: flex; align-items: center; margin-bottom: 10px; justify-content: {message_alignment};">
                    <div style="background: {message_bg_color}; color: white; border-radius: 20px; padding: 10px; margin-right: 5px; max-width: 100%; font-size: 16px;">
                        {text} \n </div>
                    <img src="{avatar_url}" class="{avatar_class}" alt="avatar" style="width: 50px; height: 50px;" />
                </div>
                """,
            unsafe_allow_html=True,
        )
    else:
        avatar_url = "https://avataaars.io/?avatarStyle=Transparent&topType=WinterHat2&accessoriesType=Wayfarers&hatColor=White&facialHairType=Blank&clotheType=Hoodie&clotheColor=Blue01&eyeType=Default&eyebrowType=RaisedExcitedNatural&mouthType=Smile&skinColor=Light"
        message_alignment = "flex-start"
        message_bg_color = "linear-gradient(90deg, hsla(236, 100%, 8%, 1) 0%, hsla(211, 100%, 28%, 1) 100%);"


        avatar_class = "bot-avatar"

        if is_df == True:
            # st.write(
            #     f"""
            #         <div style="display: flex; align-items: center; margin-bottom: 10px; justify-content: {message_alignment};">
            #             <img src="{avatar_url}" class="{avatar_class}" alt="avatar" style="width: 70px; height: 50px;" />
            #         </div>
            #         """,
            #     unsafe_allow_html=True,
            # )
            st.dataframe(text)
        elif is_image == True:
            st.image(text)
        elif is_lineage == True:
            # There was a issue with component instance using same autogenerated ID.
            # stmd.st_mermaid(text, key=f"lineage_{uuid.uuid4()}")
            try:
                st.components.v1.html(
                text,
                height=600,
                scrolling=True
                )
            except Exception as e:
                append_message(f"Error rendering lineage diagram", role="assistant")
        else:
            text = format_message(text)
            st.write(
                f"""
                    <div style="display: flex; align-items: center; margin-bottom: 10px; justify-content: {message_alignment};">
                        <img src="{avatar_url}" class="{avatar_class}" alt="avatar" style="width: 50px; height: 50px;" />
                        <div style="background: {message_bg_color}; color: white; border-radius: 18px; padding: 10px; margin-right: 5px; max-width: 100%; font-size: 16px;">
                            {text} \n </div>
                    </div>
                    """,
                unsafe_allow_html=True
            )

